### ISSUE TITLE
Improvement to Row CrossAxisAlignment

### ISSUE THREAD

**Issue by elliotrtd** [Rodiii/flutter_cupertino_setting_control#2]
Currently For a Settings Row the crossAxisAlignment is set to center only if there is neither Top Tile or Left Title. 

With a YesNo button this has the effect that the text is shown at the top of the row, but as the button is taller than the title it looks somewhat misaligned. 

> crossAxisAlignment: !widget.config.showTitleLeft &&
                                !widget.config.showTopTitle
                            ? CrossAxisAlignment.center
                            : CrossAxisAlignment.start,

https://github.com/Rodiii/flutter_cupertino_setting_control/blob/master/lib/cupertino_setting_control.dart#L753

This would probably fit better across a range of applications if aligned center?

With CrossAxisAlignment.start
![image](https://user-images.githubusercontent.com/43793032/115500890-c649e580-a2a4-11eb-86e1-69a6747b5228.png)

With CrossAxisAlignment.center
![image](https://user-images.githubusercontent.com/43793032/115500977-ed081c00-a2a4-11eb-99d1-90c12b92330e.png)

Maybe I'm missing another way to achieve this?

**Comment by Rodiii** [comment]
Hi, I've just updated the package to always crossAlign center. Thanks!
