### ISSUE TITLE
Error: Cannot run with sound null safety,

### ISSUE THREAD

**Issue by danharper83** [Rodiii/flutter_cupertino_setting_control#3]
I've added this library to a new project and I get the following error message.

    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:cupertino_setting_control
     - package:cupertino_range_slider

    For solutions, see https://dart.dev/go/unsound-null-safety

Thanks Dan

**Comment by ArielFerreiro** [comment]
+1

**Comment by Rodiii** [comment]
Hi all, please leave a comment in cupertino_range_slider as I cannot upgrade the package to support null sound safety before cupertino_range_slider is updated.

**Comment by garfieldnate** [comment]
No commits to the cupertino_range_slider repo for 4 years, and no response to the issue posted there over a year ago. I think the right thing to do here is to simply fork that project; the functionality is contained in a single file, and there are no tests. I don't think the author is coming back to it.

**Comment by Rodiii** [comment]
@garfieldnate I've just seen, that there is a plugin cupertino_range_slider_improved which already covers this. I'll switch to this one. Thanks for bringing up this ticket again.

**Comment by Rodiii** [comment]
Null-sound safety added in latest revision. Please raise a PR or a new issue if you have further topics on this.
